spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localHost:3306/awstest
    username: root
    password: iotplex
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  h2:
    console:
      enabled: true
  profiles:
    include: oauth
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1034565949993-cken3q5ieo15ev3ld424bi730iqgps08.apps.googleusercontent.com
            client-secret: iF9QedhTPBzF424lTXl9pcAP
            scope : profile,email

